#!/bin/bash
# =============================================================================
# VitalTrack - Local Development Setup Helper
# =============================================================================
# This script configures your frontend to connect to the local backend.
# 
# NOTE: The backend now uses CORS_ORIGINS=["*"] by default, so it accepts
# connections from ANY origin. You just need to tell the frontend where
# the backend is located (your computer's IP address).
# =============================================================================

set -e

echo "================================================"
echo "VitalTrack Local Development Setup"
echo "================================================"
echo ""

# Detect OS
OS="unknown"
if [[ "$OSTYPE" == "linux-gnu"* ]]; then
    OS="linux"
elif [[ "$OSTYPE" == "darwin"* ]]; then
    OS="mac"
elif [[ "$OSTYPE" == "msys" ]] || [[ "$OSTYPE" == "cygwin" ]] || [[ "$OSTYPE" == "win32" ]]; then
    OS="windows"
fi

echo "Detected OS: $OS"
echo ""

# Get local IP address
echo "Finding your local IP address..."
LOCAL_IP=""

if [[ "$OS" == "mac" ]]; then
    LOCAL_IP=$(ifconfig | grep "inet " | grep -v 127.0.0.1 | awk '{print $2}' | head -1)
elif [[ "$OS" == "linux" ]]; then
    LOCAL_IP=$(hostname -I | awk '{print $1}')
elif [[ "$OS" == "windows" ]]; then
    echo "On Windows, run: ipconfig"
    echo "Look for 'IPv4 Address' under your Wi-Fi or Ethernet adapter"
    echo ""
    read -p "Enter your IPv4 address: " LOCAL_IP
fi

if [[ -z "$LOCAL_IP" ]]; then
    echo "Could not auto-detect IP address."
    read -p "Please enter your local IP address (e.g., 192.168.1.100): " LOCAL_IP
fi

echo ""
echo "Your local IP: $LOCAL_IP"
echo ""

# Validate IP address format (basic check)
if ! [[ "$LOCAL_IP" =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
    echo "WARNING: '$LOCAL_IP' doesn't look like a valid IP address."
    echo "Expected format: 192.168.1.100"
    read -p "Continue anyway? (y/n): " CONTINUE
    if [[ "$CONTINUE" != "y" && "$CONTINUE" != "Y" ]]; then
        echo "Aborted."
        exit 1
    fi
fi

# Create frontend .env file
FRONTEND_DIR="vitaltrack-mobile"
if [[ -d "$FRONTEND_DIR" ]]; then
    echo "Creating frontend .env file..."
    cat > "$FRONTEND_DIR/.env" << EOF
# VitalTrack Mobile - Local Development Environment
# Generated by setup-local-dev.sh on $(date)
#
# This tells the mobile app where to find the backend API.
# Your backend should be running at: http://${LOCAL_IP}:8000

EXPO_PUBLIC_API_URL=http://${LOCAL_IP}:8000
EOF
    echo "✅ Created: $FRONTEND_DIR/.env"
else
    echo "❌ ERROR: Frontend directory '$FRONTEND_DIR' not found!"
    echo "   Make sure you're running this script from the project root."
    exit 1
fi

# Verify backend directory exists
BACKEND_DIR="vitaltrack-backend"
if [[ ! -d "$BACKEND_DIR" ]]; then
    echo "❌ WARNING: Backend directory '$BACKEND_DIR' not found!"
fi

echo ""
echo "================================================"
echo "✅ Setup Complete!"
echo "================================================"
echo ""
echo "Your configuration:"
echo "  - Backend URL: http://${LOCAL_IP}:8000"
echo "  - Frontend .env: $FRONTEND_DIR/.env"
echo ""
echo "IMPORTANT: Your phone and computer must be on the SAME WiFi network!"
echo ""
echo "Next steps:"
echo ""
echo "  STEP 1 - Start the backend (in terminal 1):"
echo "    cd vitaltrack-backend"
echo "    docker-compose up --build"
echo ""
echo "  STEP 2 - Wait for this message:"
echo "    'vitaltrack-api | Database tables created/verified'"
echo ""
echo "  STEP 3 - Verify backend is running:"
echo "    Open in browser: http://${LOCAL_IP}:8000/health"
echo "    (Should show JSON with 'status: healthy')"
echo ""
echo "  STEP 4 - Start the frontend (in terminal 2):"
echo "    cd vitaltrack-mobile"
echo "    npm install --legacy-peer-deps"
echo "    npx expo start --clear"
echo ""
echo "  STEP 5 - Test on your phone:"
echo "    - Open Expo Go app"
echo "    - Scan the QR code"
echo "    - Try registering a new account"
echo ""
echo "Troubleshooting:"
echo "  - 'Network request failed': Check phone/computer on same WiFi"
echo "  - 'Connection refused': Is Docker running? Check 'docker-compose ps'"
echo "  - Still failing? Try: http://${LOCAL_IP}:8000/health in phone browser"
echo ""
