@echo off
REM =============================================================================
REM VitalTrack - Local Development Setup Helper (Windows)
REM =============================================================================
REM This script configures your frontend to connect to the local backend.
REM 
REM NOTE: The backend now uses CORS_ORIGINS=["*"] by default, so it accepts
REM connections from ANY origin. You just need to tell the frontend where
REM the backend is located (your computer's IP address).
REM =============================================================================

echo ================================================
echo VitalTrack Local Development Setup (Windows)
echo ================================================
echo.

REM Get local IP - try to auto-detect
echo Finding your local IP address...
echo.

set LOCAL_IP=
for /f "tokens=2 delims=:" %%a in ('ipconfig ^| findstr /i "IPv4" ^| findstr /i /v "127.0.0.1"') do (
    if not defined LOCAL_IP (
        set LOCAL_IP=%%a
    )
)

REM Trim leading space
if defined LOCAL_IP (
    set LOCAL_IP=%LOCAL_IP:~1%
)

if not defined LOCAL_IP (
    echo Could not auto-detect IP address.
    echo.
    echo Run 'ipconfig' and look for 'IPv4 Address' under your WiFi adapter.
    echo.
    set /p LOCAL_IP="Enter your IPv4 address (e.g., 192.168.1.100): "
) else (
    echo Your local IP appears to be: %LOCAL_IP%
    echo.
    set /p CONFIRM_IP="Press Enter to confirm, or type a different IP: "
    if not "%CONFIRM_IP%"=="" set LOCAL_IP=%CONFIRM_IP%
)

echo.
echo Using IP: %LOCAL_IP%
echo.

REM Validate frontend directory exists
if not exist "vitaltrack-mobile" (
    echo ERROR: vitaltrack-mobile folder not found!
    echo Make sure you're running this script from the project root.
    pause
    exit /b 1
)

REM Create frontend .env
echo Creating frontend .env file...
(
echo # VitalTrack Mobile - Local Development Environment
echo # Generated by setup-local-dev.bat
echo #
echo # This tells the mobile app where to find the backend API.
echo.
echo EXPO_PUBLIC_API_URL=http://%LOCAL_IP%:8000
) > vitaltrack-mobile\.env

echo [OK] Created: vitaltrack-mobile\.env
echo.

echo.
echo ================================================
echo [SUCCESS] Setup Complete!
echo ================================================
echo.
echo Your configuration:
echo   - Backend URL: http://%LOCAL_IP%:8000
echo   - Frontend .env: vitaltrack-mobile\.env
echo.
echo IMPORTANT: Your phone and computer must be on the SAME WiFi network!
echo.
echo Next steps:
echo.
echo   STEP 1 - Start the backend (in Command Prompt 1):
echo     cd vitaltrack-backend
echo     docker-compose up --build
echo.
echo   STEP 2 - Wait for this message:
echo     'vitaltrack-api : Database tables created/verified'
echo.
echo   STEP 3 - Verify backend is running:
echo     Open in browser: http://%LOCAL_IP%:8000/health
echo.
echo   STEP 4 - Start the frontend (in Command Prompt 2):
echo     cd vitaltrack-mobile
echo     npm install
echo     npx expo start --clear
echo.
echo   STEP 5 - Test on your phone:
echo     - Open Expo Go app
echo     - Scan the QR code
echo     - Try registering a new account
echo.
echo Troubleshooting:
echo   - Network request failed: Check phone/computer on same WiFi
echo   - Connection refused: Is Docker running?
echo   - Firewall: Allow port 8000 through Windows Firewall
echo.
pause
