/* eslint-env node */
const assert=require('node:assert/strict');const {test}=require('node:test');const fs=require('node:fs');const path=require('node:path');const vm=require('node:vm');const ts=require('typescript');
function load(file,deps={}){const m={exports:{}};const code=ts.transpileModule(fs.readFileSync(path.join(__dirname,'..',file),'utf8'),{fileName:file,compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020}}).outputText;vm.runInNewContext(code,{module:m,exports:m.exports,Date,Map,require:n=>{if(n in deps)return deps[n];throw new Error('Unexpected import '+n);}});return m.exports;}
function harness({copyFails=false,sharing=true,cancelAtPrint=false}={}){const calls={html:[],shared:[],copies:[]};let valid=true;const escapeHtml=s=>String(s||'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');const fileSystem={documentDirectory:'file:///documents/',readAsStringAsync:async()=>'',copyAsync:async v=>{calls.copies.push(v);if(copyFails)throw new Error('Copy failed');}};const deps={'expo-print':{printToFileAsync:async({html})=>{calls.html.push(html);if(cancelAtPrint)valid=false;return{uri:'file:///cache/real.pdf'};}},'expo-sharing':{isAvailableAsync:async()=>sharing,shareAsync:async uri=>{calls.shared.push(uri);}},'expo-file-system/legacy':fileSystem,'react-native':{Alert:{alert(){}}},'@/utils/sanitize':{escapeHtml,validateImageUri:()=>null},'@/utils/helpers':{formatDate:s=>s,now:()=>new Date().toISOString()},'@/types':load('types/index.ts'),'@/utils/logger':{logger:{warn(){}}}};return {calls,inventory:load('utils/inventoryPdfExport.ts',deps),order:load('utils/orderPdfExport.ts',deps),ready(){if(!valid)throw new Error('Session changed');}};}
const items=[{id:'a',name:'<Gloves>',quantity:2,minimumStock:5,unit:'pairs',categoryId:'missing',isActive:true},{id:'b',name:'Masks',quantity:0,minimumStock:5,unit:'boxes',categoryId:'known',isActive:true}];
test('inventory PDF keeps unknown-category rows, uses reviewed facts and escapes names',async()=>{const h=harness();await h.inventory.exportInventoryPdf({items,categories:[{id:'known',name:'Wound care'}],includePhotos:false,timestamp:100,stale:true});const html=h.calls.html[0];assert.match(html,/&lt;Gloves&gt;/);assert.match(html,/Masks/);assert.match(html,/Category name unavailable/);assert.match(html,/Last-known\/offline snapshot/);assert.match(html,/2 items in the reviewed view/);assert.doesNotMatch(html,/<Gloves>/);});
test('failed report rename shares the real original file, never a nonexistent destination',async()=>{const h=harness({copyFails:true});const result=await h.inventory.exportInventoryPdf({items,categories:[],includePhotos:false});assert.equal(result.uri,'file:///cache/real.pdf');assert.deepEqual(h.calls.shared,['file:///cache/real.pdf']);});
test('unavailable sharing is reported as generated only',async()=>{const h=harness({sharing:false});const result=await h.order.exportOrderPdf({id:'ORD-1',items},false);assert.equal(result.shared,false);assert.equal(h.calls.shared.length,0);});
test('order PDF escapes title/links and has no write service',async()=>{const h=harness();await h.order.exportOrderPdf({id:'ORD-<1>',items:[{...items[0],purchaseLink:'https://example.test/" onclick="bad'}]},false);const html=h.calls.html[0];assert.match(html,/ORD-&lt;1&gt;/);assert.doesNotMatch(html,/href="[^"\n]*" onclick=/);});
test('session changes after rendering prevent sharing old-account data',async()=>{const h=harness({cancelAtPrint:true});await assert.rejects(h.inventory.exportInventoryPdf({items,categories:[],includePhotos:false,assertReady:h.ready}),/Session changed/);assert.equal(h.calls.shared.length,0);});
