"""VitalTrack Backend - Pydantic Schemas"""

from app.schemas.category import (
    CategoryCreate,
    CategoryList,
    CategoryResponse,
    CategoryUpdate,
    CategoryWithCount,
)
from app.schemas.common import (
    DashboardStats,
    ErrorDetail,
    ErrorResponse,
    HealthCheck,
    PaginatedResponse,
    SuccessResponse,
)
from app.schemas.item import (
    ItemBrief,
    ItemCreate,
    ItemList,
    ItemResponse,
    ItemStats,
    ItemUpdate,
    StockUpdate,
)
from app.schemas.order import (
    OrderBrief,
    OrderCreate,
    OrderItemCreate,
    OrderItemResponse,
    OrderList,
    OrderResponse,
    OrderStatusUpdate,
)
from app.schemas.sync import (
    ConflictResolution,
    FullSyncRequest,
    FullSyncResponse,
    SyncConflict,
    SyncEntityType,
    SyncOperation,
    SyncOperationResult,
    SyncOperationType,
    SyncPullRequest,
    SyncPullResponse,
    SyncPushRequest,
    SyncPushResponse,
)
from app.schemas.user import (
    AuthResponse,
    EmailVerificationRequest,
    ForgotPasswordRequest,
    MessageResponse,
    PasswordChange,
    PasswordReset,
    PasswordResetConfirm,
    ResetPasswordRequest,
    TokenRefresh,
    UserBrief,
    UserLogin,
    UserRegister,
    UserResponse,
    UserUpdate,
    VerifyEmailResponse,
)

__all__ = [
    # User
    "AuthResponse",
    "EmailVerificationRequest",
    "ForgotPasswordRequest",
    "MessageResponse",
    "PasswordChange",
    "PasswordReset",
    "PasswordResetConfirm",
    "ResetPasswordRequest",
    "TokenRefresh",
    "UserBrief",
    "UserLogin",
    "UserRegister",
    "UserResponse",
    "UserUpdate",
    "VerifyEmailResponse",
    # Category
    "CategoryCreate",
    "CategoryList",
    "CategoryResponse",
    "CategoryUpdate",
    "CategoryWithCount",
    # Item
    "ItemBrief",
    "ItemCreate",
    "ItemList",
    "ItemResponse",
    "ItemStats",
    "ItemUpdate",
    "StockUpdate",
    # Order
    "OrderBrief",
    "OrderCreate",
    "OrderItemCreate",
    "OrderItemResponse",
    "OrderList",
    "OrderResponse",
    "OrderStatusUpdate",
    # Sync
    "ConflictResolution",
    "FullSyncRequest",
    "FullSyncResponse",
    "SyncConflict",
    "SyncEntityType",
    "SyncOperation",
    "SyncOperationResult",
    "SyncOperationType",
    "SyncPullRequest",
    "SyncPullResponse",
    "SyncPushRequest",
    "SyncPushResponse",
    # Common
    "DashboardStats",
    "ErrorDetail",
    "ErrorResponse",
    "HealthCheck",
    "PaginatedResponse",
    "SuccessResponse",
]
