/**
 * VitalTrack Mobile - Order PDF Export Utility
 * Shared between order creation and order list screens.
 * Supports Table PDF and Card PDF (with images) formats.
 */

import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';
import { readAsStringAsync } from 'expo-file-system/legacy';
import { Alert } from 'react-native';
import { escapeHtml, validateImageUri } from '@/utils/sanitize';
import { formatDate, now } from '@/utils/helpers';
import type { OrderItem } from '@/types';

interface ExportableOrder {
  id: string;
  items: OrderItem[];
  createdAt?: string;
}

/**
 * Convert local image URI to base64 data URL for PDF embedding
 */
async function getBase64Image(uri: string): Promise<string> {
  try {
    const validUri = validateImageUri(uri);
    if (!validUri) return '';
    if (validUri.startsWith('data:')) return validUri;

    let fileUri = validUri;
    if (!validUri.startsWith('file://') && !validUri.startsWith('content://')) {
      fileUri = validUri.startsWith('/') ? `file://${validUri}` : validUri;
    }

    const base64 = await readAsStringAsync(fileUri, { encoding: 'base64' });
    const ext = validUri.split('.').pop()?.toLowerCase() || 'jpeg';
    const mimeType = ext === 'png' ? 'image/png' : ext === 'gif' ? 'image/gif' : 'image/jpeg';
    return `data:${mimeType};base64,${base64}`;
  } catch {
    return '';
  }
}

/**
 * Generate Table PDF (no images) and share
 */
export async function generateTablePDF(order: ExportableOrder): Promise<void> {
  const { id: orderId, items } = order;
  const currentDate = order.createdAt || formatDate(now());
  const totalItems = items.length;
  const totalUnits = items.reduce((sum, i) => sum + i.quantity, 0);

  const html = `
    <!DOCTYPE html>
    <html>
      <head>
        <meta charset="utf-8">
        <style>
          * { box-sizing: border-box; margin: 0; padding: 0; }
          body { font-family: 'Segoe UI', -apple-system, sans-serif; padding: 25px; color: #1a1a1a; background: #fff; font-size: 15px; }
          .header { text-align: center; margin-bottom: 20px; padding-bottom: 15px; border-bottom: 3px solid #3b5998; }
          h1 { font-size: 28px; color: #3b5998; margin-bottom: 5px; }
          .order-id { font-size: 15px; color: #666; }
          .meta { color: #888; font-size: 14px; }
          .summary { background: #f0f4ff; padding: 14px 20px; border-radius: 8px; margin-bottom: 20px; text-align: center; font-size: 15px; color: #3b5998; }
          table { width: 100%; border-collapse: collapse; }
          th { background: #3b5998; color: white; padding: 14px 10px; text-align: left; font-weight: 600; font-size: 14px; }
          th:first-child { width: 40px; text-align: center; }
          th:nth-child(4) { text-align: center; }
          th:last-child { text-align: center; }
          td { padding: 14px 10px; border-bottom: 1px solid #e8e8f0; font-size: 14px; vertical-align: middle; }
          tr:nth-child(even) { background: #f8f9fc; }
          td:first-child { text-align: center; color: #666; }
          td:nth-child(4) { text-align: center; font-weight: 700; color: #3b5998; }
          td:last-child { text-align: center; }
          .item-name { font-weight: 600; color: #1a1a1a; }
          .empty { color: #999; }
          .link-btn { color: #3b5998; text-decoration: none; font-size: 13px; }
          .footer { margin-top: 25px; text-align: center; font-size: 12px; color: #888; padding-top: 15px; border-top: 1px solid #e8e8f0; }
          .footer-brand { color: #3b5998; font-weight: 600; }
        </style>
      </head>
      <body>
        <div class="header">
          <h1>Purchase Order</h1>
          <div class="order-id">Order #${escapeHtml(orderId)}</div>
          <div class="meta">${escapeHtml(currentDate)}</div>
        </div>
        <div class="summary"><strong>${totalItems}</strong> Items to Order  •  <strong>${totalUnits}</strong> Total Units</div>
        <table>
          <thead>
            <tr><th>#</th><th>Item Name</th><th>Brand</th><th>Qty</th><th>Supplier</th><th>Link</th></tr>
          </thead>
          <tbody>
            ${items.map((item, idx) => `
              <tr>
                <td>${idx + 1}</td>
                <td><span class="item-name">${escapeHtml(item.name)}</span></td>
                <td>${escapeHtml(item.brand || '') || '<span class="empty">-</span>'}</td>
                <td>${item.quantity} ${escapeHtml(item.unit)}</td>
                <td>${escapeHtml(item.supplierName || '') || '<span class="empty">-</span>'}</td>
                <td>${item.purchaseLink ? '<a href="' + encodeURI(item.purchaseLink) + '" class="link-btn">Link</a>' : '<span class="empty">-</span>'}</td>
              </tr>
            `).join('')}
          </tbody>
        </table>
        <div class="footer">Generated by <span class="footer-brand">VitalTrack</span></div>
      </body>
    </html>
  `;

  const { uri } = await Print.printToFileAsync({ html });
  if (await Sharing.isAvailableAsync()) {
    await Sharing.shareAsync(uri, { UTI: 'com.adobe.pdf', mimeType: 'application/pdf', dialogTitle: `Order ${orderId}` });
  }
}

/**
 * Generate Card PDF (with images) and share
 */
export async function generateCardPDF(order: ExportableOrder): Promise<void> {
  const { id: orderId, items } = order;
  const currentDate = order.createdAt || formatDate(now());
  const totalItems = items.length;
  const totalUnits = items.reduce((sum, i) => sum + i.quantity, 0);

  // Convert images to base64
  const itemsWithImages = await Promise.all(
    items.map(async (item) => ({
      ...item,
      imageBase64: item.imageUri ? await getBase64Image(item.imageUri) : '',
    }))
  );

  const html = `
    <!DOCTYPE html>
    <html>
      <head>
        <meta charset="utf-8">
        <style>
          * { box-sizing: border-box; margin: 0; padding: 0; }
          body {
            font-family: 'Segoe UI', -apple-system, sans-serif;
            padding: 30px; color: #1a1a1a; background: #fff; line-height: 1.4; font-size: 15px;
          }
          .header { text-align: center; margin-bottom: 30px; padding-bottom: 20px; border-bottom: 3px solid #1e3a5f; }
          h1 { font-size: 28px; color: #1e3a5f; font-weight: 700; margin-bottom: 8px; }
          .order-id { font-size: 16px; color: #64748b; margin-bottom: 5px; }
          .meta { color: #888; font-size: 14px; }
          .summary-bar {
            display: flex; justify-content: center; gap: 40px;
            background: linear-gradient(135deg, #1e3a5f 0%, #2d5a7b 100%);
            color: white; padding: 18px 30px; border-radius: 12px; margin-bottom: 30px;
          }
          .summary-item { text-align: center; }
          .summary-value { font-size: 28px; font-weight: 700; }
          .summary-label { font-size: 13px; opacity: 0.9; }
          .item-card {
            display: flex; flex-direction: row; margin-bottom: 25px;
            border: 1px solid #e0e0e0; border-radius: 12px; overflow: hidden;
            background: #fafafa; page-break-inside: avoid; min-height: 280px;
          }
          .item-main { flex: 0 0 55%; padding: 20px; display: flex; flex-direction: column; gap: 15px; }
          .item-name { font-size: 18px; font-weight: 700; color: #1e3a5f; padding-bottom: 10px; border-bottom: 2px solid #f1f5f9; }
          .details-grid { display: grid; grid-template-columns: 1fr 1fr; border: 1px solid #e2e8f0; border-radius: 8px; overflow: hidden; background: #fff; }
          .detail-box { padding: 14px; border-right: 1px solid #e2e8f0; border-bottom: 1px solid #e2e8f0; display: flex; flex-direction: column; justify-content: center; }
          .detail-box:nth-child(2n) { border-right: none; }
          .detail-box:nth-child(n+3) { border-bottom: none; }
          .detail-label { font-size: 13px; color: #64748b; text-transform: uppercase; letter-spacing: 0.5px; margin-bottom: 4px; font-weight: 600; }
          .detail-value { font-size: 16px; font-weight: 600; color: #334155; }
          .link-btn { display: inline-block; background: #f1f5f9; color: #1e3a5f; padding: 6px 12px; border-radius: 4px; font-size: 13px; text-decoration: none; font-weight: 600; border: 1px solid #e2e8f0; }
          .item-image { flex: 0 0 45%; background: #fff; border-left: 1px solid #e0e0e0; display: flex; align-items: center; justify-content: center; padding: 12px; }
          .item-image img { width: 100%; height: 100%; object-fit: cover; max-height: 280px; border-radius: 8px; }
          .footer { margin-top: 40px; text-align: center; font-size: 12px; color: #888; padding-top: 20px; border-top: 2px solid #e8e8e8; }
          .footer-brand { font-weight: 600; color: #1e3a5f; }
        </style>
      </head>
      <body>
        <div class="header">
          <h1>Purchase Order</h1>
          <div class="order-id">Order #${escapeHtml(orderId)}</div>
          <div class="meta">${escapeHtml(currentDate)}</div>
        </div>
        <div class="summary-bar">
          <div class="summary-item"><div class="summary-value">${totalItems}</div><div class="summary-label">Items</div></div>
          <div class="summary-item"><div class="summary-value">${totalUnits}</div><div class="summary-label">Total Units</div></div>
        </div>
        ${itemsWithImages.map((item, index) => `
          <div class="item-card">
            <div class="item-main">
              <div class="item-name"><span style="color: #64748b; font-weight: 400;">${index + 1}.</span> ${escapeHtml(item.name)}</div>
              <div class="details-grid">
                <div class="detail-box">
                  <div class="detail-label">Order Qty</div>
                  <div class="detail-value" style="font-size: 17px; color: #1e3a5f;">${item.quantity} ${escapeHtml(item.unit)}</div>
                </div>
                <div class="detail-box">
                  <div class="detail-label">Brand</div>
                  <div class="detail-value">${escapeHtml(item.brand || '') || '—'}</div>
                </div>
                <div class="detail-box">
                  <div class="detail-label">Supplier</div>
                  <div class="detail-value">${escapeHtml(item.supplierName || '') || '—'}</div>
                </div>
                <div class="detail-box">
                  <div class="detail-label">Link</div>
                  ${item.purchaseLink ? `<a href="${encodeURI(item.purchaseLink)}" class="link-btn">Buy Now</a>` : '<div class="detail-value">—</div>'}
                </div>
              </div>
            </div>
            ${item.imageBase64 ? `<div class="item-image"><img src="${item.imageBase64}" alt="${escapeHtml(item.name)}"/></div>` : ''}
          </div>
        `).join('')}
        <div class="footer">Generated by <span class="footer-brand">VitalTrack</span> • Home ICU Inventory Management</div>
      </body>
    </html>
  `;

  const { uri } = await Print.printToFileAsync({ html });
  if (await Sharing.isAvailableAsync()) {
    await Sharing.shareAsync(uri, { UTI: 'com.adobe.pdf', mimeType: 'application/pdf', dialogTitle: `Order ${orderId}` });
  }
}

/**
 * Show PDF format selection dialog and export
 */
export function showPdfExportDialog(order: ExportableOrder): void {
  if (order.items.length === 0) {
    Alert.alert('No Items', 'This order has no items to export.');
    return;
  }
  Alert.alert(
    'Export PDF Format',
    'Choose your preferred layout:',
    [
      { text: 'Cancel', style: 'cancel' },
      {
        text: 'Table (No Images)',
        onPress: async () => {
          try {
            await generateTablePDF(order);
          } catch (e) {
            console.error(e);
            Alert.alert('Error', 'Failed to generate PDF');
          }
        },
      },
      {
        text: 'Cards (With Images)',
        onPress: async () => {
          try {
            await generateCardPDF(order);
          } catch (e) {
            console.error(e);
            Alert.alert('Error', 'Failed to generate PDF');
          }
        },
      },
    ]
  );
}
